/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgfinal.java;

//import java.text.DateFormat;
//import java.text.SimpleDateFormat;
//import java.util.Date;
import java.sql.*;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.text.SimpleDateFormat;
//import java.sql.SQLException;
//import java.sql.ResultSet;




/**
 *
 * @author DELL
 */
public class addpurchase extends javax.swing.JFrame {
    static String bb1,bb2;

    /**
     * Creates new form addpurchase
     */
    public addpurchase() {
        initComponents();
        
    }
    
    
     public addpurchase(String para) {
        initComponents();

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        invoiceamnt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        mino = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        qtyreceived = new javax.swing.JTextField();
        serialno = new javax.swing.JTextField();
        remainingqnty = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        receivedby = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        ac = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        quantities = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        invoiceno = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        datereceived = new com.toedter.calendar.JDateChooser();
        dateofentry = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        a = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel13.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel13.setText("Received By");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(500, 610, 190, 30);

        invoiceamnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invoiceamntActionPerformed(evt);
            }
        });
        invoiceamnt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                invoiceamntKeyReleased(evt);
            }
        });
        getContentPane().add(invoiceamnt);
        invoiceamnt.setBounds(700, 250, 334, 50);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Purchase Entry");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 236, 45);

        mino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                minoKeyReleased(evt);
            }
        });
        getContentPane().add(mino);
        mino.setBounds(700, 390, 334, 50);

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel2.setText("Serial No.");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 550, 190, 30);

        qtyreceived.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qtyreceivedKeyReleased(evt);
            }
        });
        getContentPane().add(qtyreceived);
        qtyreceived.setBounds(700, 460, 334, 50);

        serialno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                serialnoKeyReleased(evt);
            }
        });
        getContentPane().add(serialno);
        serialno.setBounds(240, 540, 230, 50);

        remainingqnty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                remainingqntyKeyReleased(evt);
            }
        });
        getContentPane().add(remainingqnty);
        remainingqnty.setBounds(700, 530, 334, 50);

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel3.setText("Date Ordered");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 620, 220, 30);
        getContentPane().add(receivedby);
        receivedby.setBounds(700, 600, 334, 50);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setText("SAVE ENTRY");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(700, 680, 111, 70);

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel4.setText("Category");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 410, 180, 30);

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel5.setText("Product");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 330, 180, 30);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton3.setText("CANCEL");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(950, 680, 81, 72);

        ac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        ac.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                acKeyReleased(evt);
            }
        });
        getContentPane().add(ac);
        ac.setBounds(240, 400, 230, 50);

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel6.setText("Quantity");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(500, 200, 170, 30);

        quantities.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                quantitiesKeyReleased(evt);
            }
        });
        getContentPane().add(quantities);
        quantities.setBounds(700, 180, 334, 50);

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel7.setText("Invoice No.");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 690, 200, 30);

        invoiceno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                invoicenoKeyReleased(evt);
            }
        });
        getContentPane().add(invoiceno);
        invoiceno.setBounds(240, 680, 230, 50);

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel8.setText("Invoice Amount");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(500, 270, 190, 30);

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel9.setText("Date Received");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(500, 340, 190, 30);

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel10.setText("MI No.");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(500, 410, 150, 30);

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel11.setText("Qty. Received");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(500, 480, 190, 30);

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel12.setText("Remaining Qty");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(500, 550, 190, 30);

        jButton4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton4.setText("CLEAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(840, 680, 81, 70);

        jLabel14.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel14.setText("Party Name");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(10, 270, 200, 20);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(240, 250, 230, 50);

        jLabel15.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel15.setText("New Due");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(500, 110, 150, 30);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(700, 110, 330, 50);

        datereceived.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                datereceivedKeyReleased(evt);
            }
        });
        getContentPane().add(datereceived);
        datereceived.setBounds(700, 320, 334, 50);
        getContentPane().add(dateofentry);
        dateofentry.setBounds(240, 610, 230, 50);

        jLabel16.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel16.setText("Distributor ID");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(10, 190, 190, 30);

        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField3KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(240, 180, 230, 50);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField4KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(240, 320, 230, 50);

        jLabel17.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel17.setText("Sub Category");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(10, 480, 210, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        jComboBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jComboBox1KeyReleased(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(240, 470, 230, 50);

        a.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        a.setText("Purchase ID");
        getContentPane().add(a);
        a.setBounds(10, 110, 190, 30);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(240, 100, 230, 50);

        setSize(new java.awt.Dimension(1104, 818));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         Connection conn;
         ResultSet rs=null;
         PreparedStatement pst;
           SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
        String xyz=sdf.format(datereceived.getDate());
         String mno=sdf.format(dateofentry.getDate());
       
         
         try{
             Class.forName("com.mysql.jdbc.Driver");
             
             conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/mis","root","");
             String sql;
                sql = "Insert into purchase(Purchase_Id,Distributor_Id,Sl,Party_Name,Product,Category,Sub_Category,Invoice,Order_Date,Amount,Recieve_Date,Quantity,Quantity_Recieved,Remaining_Quantity,Mi_No,Recieved_By,New_Due) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
                
             pst = conn.prepareStatement(sql);
              pst.setString(1,jTextField5.getText());
              pst.setString(2,jTextField3.getText());
              pst.setString(3,serialno.getText());
              pst.setString(4,jTextField1.getText());
                 pst.setString(5,jTextField4.getText());
              pst.setString(6,ac.getSelectedItem().toString());
              pst.setString(7,jComboBox1.getSelectedItem().toString());
               pst.setString(8,invoiceno.getText());
           
             pst.setString(9,mno);
              pst.setString(10,invoiceamnt.getText());
             pst.setString(11,xyz);
              pst.setString(12,quantities.getText());
               pst.setString(13,qtyreceived.getText());
              pst.setString(14,remainingqnty.getText());
              pst.setString(15,mino.getText());
              pst.setString(16,receivedby.getText());
              pst.setString(17,jTextField2.getText());
             
              
              pst.execute();
              
              JOptionPane.showMessageDialog(null,"saved");
            }
         catch(Exception e)
         {
              JOptionPane.showMessageDialog(null, "PLEASE CHECK THE FIELDS AGAIN");
                       
          }
            try{
        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","");
    String sql="select Quantity from product where Title=?";
    
    pst=conn.prepareStatement(sql);
    pst.setString(1,jTextField4.getText());
    //  pst.setString(2,ac.getSelectedItem().toString());
       // pst.setString(3,jComboBox1.getSelectedItem().toString());
        rs=pst.executeQuery();
        if(rs.next())
        {
            int ad=rs.getInt("Quantity");
          bb1= qtyreceived.getText();
           int mn=rs.getInt(bb1);
         int   op=ad+mn;
           String k=op+" ";
            sql="UPDATE product set Quantity='k'  where Title=?" ;
                     pst.setString(1,jTextField4.getText()); 
        }
    
    
     }
    catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
        
         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        serialno.setText("  ");
        jTextField5.setText("  ");
        jTextField4.setText("  ");
        quantities.setText("  ");
        invoiceno.setText("  ");
        invoiceamnt.setText("  ");
        mino.setText("  ");
        qtyreceived.setText("  ");
        remainingqnty.setText("  ");
        receivedby.setText("  ");
        ac.setSelectedIndex(0);
        jComboBox1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void serialnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_serialnoKeyReleased
        // TODO add your handling code here:
        
int key=evt.getKeyCode();
    if(key==10)
    {
    dateofentry.requestFocus();// TODO add your handling code here:
    }
    }//GEN-LAST:event_serialnoKeyReleased

    private void acKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_acKeyReleased
        // TODO add your handling code here:
        int key=evt.getKeyCode();
    if(key==10)
    {
    jComboBox1.requestFocus();// TODO add your handling code here:
    }


    }//GEN-LAST:event_acKeyReleased

    private void quantitiesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantitiesKeyReleased
        // TODO add your handling code here:
        
int key=evt.getKeyCode();
    if(key==10)
    {
    invoiceamnt.requestFocus();// TODO add your handling code here:
    }

    }//GEN-LAST:event_quantitiesKeyReleased

    private void invoicenoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_invoicenoKeyReleased
        // TODO add your handling code here:
        
int key=evt.getKeyCode();
    if(key==10)
    {
    jTextField2.requestFocus();// TODO add your handling code here:
    }

    }//GEN-LAST:event_invoicenoKeyReleased

    private void invoiceamntKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_invoiceamntKeyReleased
        // TODO add your handling code here:
        
int key=evt.getKeyCode();
    if(key==10)
    {
    datereceived.requestFocus();// TODO add your handling code here:
    }

    }//GEN-LAST:event_invoiceamntKeyReleased

    private void minoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_minoKeyReleased
        // TODO add your handling code here:
        
int key=evt.getKeyCode();
    if(key==10)
    {
    qtyreceived.requestFocus();// TODO add your handling code here:
    }

    }//GEN-LAST:event_minoKeyReleased

    private void qtyreceivedKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyreceivedKeyReleased
        // TODO add your handling code here:
int key=evt.getKeyCode();
    if(key==10)
    {
    remainingqnty.requestFocus();// TODO add your handling code here:
    }

    }//GEN-LAST:event_qtyreceivedKeyReleased

    private void remainingqntyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_remainingqntyKeyReleased
        // TODO add your handling code here:
int key=evt.getKeyCode();
    if(key==10)
    {
    receivedby.requestFocus();// TODO add your handling code here:
    }

    }//GEN-LAST:event_remainingqntyKeyReleased

    private void jComboBox1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox1KeyReleased
        // TODO add your handling code here:
        int key=evt.getKeyCode();
    if(key==10)
    {
    serialno.requestFocus();// TODO add your handling code here:
    }
    }//GEN-LAST:event_jComboBox1KeyReleased

    private void jTextField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyReleased
        // TODO add your handling code here:
         int key=evt.getKeyCode();
    if(key==10)
    {
    jTextField1.requestFocus();// TODO add your handling code here:
    }
    }//GEN-LAST:event_jTextField3KeyReleased

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
         int key=evt.getKeyCode();
    if(key==10)
    {
    jTextField4.requestFocus();// TODO add your handling code here:
    }
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTextField4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyReleased
        // TODO add your handling code here:
         int key=evt.getKeyCode();
    if(key==10)
    {
    ac.requestFocus();// TODO add your handling code here:
    }
    }//GEN-LAST:event_jTextField4KeyReleased

    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
        // TODO add your handling code here:
         int key=evt.getKeyCode();
    if(key==10)
    {
    quantities.requestFocus();// TODO add your handling code here:
    }
    }//GEN-LAST:event_jTextField2KeyReleased

    private void datereceivedKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_datereceivedKeyReleased
        // TODO add your handling code here:
         int key=evt.getKeyCode();
    if(key==10)
    {
    mino.requestFocus();// TODO add your handling code here:
    }
    }//GEN-LAST:event_datereceivedKeyReleased

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void invoiceamntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invoiceamntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_invoiceamntActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addpurchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addpurchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addpurchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addpurchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new addpurchase().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a;
    private javax.swing.JComboBox<String> ac;
    private com.toedter.calendar.JDateChooser dateofentry;
    private com.toedter.calendar.JDateChooser datereceived;
    private javax.swing.JTextField invoiceamnt;
    private javax.swing.JTextField invoiceno;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField mino;
    private javax.swing.JTextField qtyreceived;
    private javax.swing.JTextField quantities;
    private javax.swing.JTextField receivedby;
    private javax.swing.JTextField remainingqnty;
    public javax.swing.JTextField serialno;
    // End of variables declaration//GEN-END:variables

    private void setText(String __) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
