/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgfinal.java;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.sql.*;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
/**
 *
 * @author DELL
 */
public class addsale extends javax.swing.JFrame {

    /**
     * Creates new form addsale
     */
    public addsale() {
        initComponents();
       
    }
    
    
     public addsale(String para) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        h = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        d = new javax.swing.JTextField();
        e = new javax.swing.JTextField();
        f = new javax.swing.JTextField();
        g = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        i = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        j = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        k = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        ac = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        a = new javax.swing.JTextField();
        c = new javax.swing.JTextField();
        h1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        b = new com.toedter.calendar.JDateChooser();
        i1 = new com.toedter.calendar.JDateChooser();
        jLabel17 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();

        jLabel18.setIcon(new javax.swing.ImageIcon("C:\\New folder (2)\\115274.jpg")); // NOI18N
        jLabel18.setText("jLabel18");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        d.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dKeyReleased(evt);
            }
        });
        getContentPane().add(d);
        d.setBounds(320, 480, 190, 50);

        e.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                eKeyReleased(evt);
            }
        });
        getContentPane().add(e);
        e.setBounds(320, 540, 190, 50);

        f.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fKeyReleased(evt);
            }
        });
        getContentPane().add(f);
        f.setBounds(320, 600, 190, 50);

        g.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                gKeyReleased(evt);
            }
        });
        getContentPane().add(g);
        g.setBounds(890, 250, 190, 50);

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel10.setText("Quantity");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(560, 140, 230, 30);

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel11.setText("Date Of Invoice");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(560, 330, 280, 30);

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel12.setText("Dispatched Quantity");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(560, 200, 320, 30);

        jLabel13.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel13.setText("Gate Pass No.");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(560, 380, 270, 30);

        jLabel14.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel14.setText("Material Outward No.");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(560, 430, 330, 30);

        i.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                iKeyReleased(evt);
            }
        });
        getContentPane().add(i);
        i.setBounds(890, 180, 190, 50);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Sales Entry");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 262, 32);

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel2.setText("No. Of Entry");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(560, 490, 260, 30);

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel3.setText("Date Of Entry");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 440, 230, 30);

        j.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jKeyReleased(evt);
            }
        });
        getContentPane().add(j);
        j.setBounds(890, 370, 190, 50);

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel4.setText("Category");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 320, 220, 20);
        getContentPane().add(k);
        k.setBounds(890, 430, 190, 50);

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel5.setText("Product");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 260, 190, 20);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("SAVE SALES");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(600, 620, 107, 55);

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel6.setText("Invoice No");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 500, 210, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("CLEAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(740, 620, 73, 55);

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel7.setText("Product Amount");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 550, 260, 30);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton3.setText("CANCEL");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(860, 620, 81, 50);

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel8.setText("Dispatched Through");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 610, 270, 30);

        ac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        ac.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                acKeyReleased(evt);
            }
        });
        getContentPane().add(ac);
        ac.setBounds(320, 300, 190, 50);

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel9.setText("Remaining Quantity");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(560, 270, 300, 30);

        a.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                aKeyReleased(evt);
            }
        });
        getContentPane().add(a);
        a.setBounds(890, 490, 190, 50);

        c.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cKeyReleased(evt);
            }
        });
        getContentPane().add(c);
        c.setBounds(320, 240, 190, 50);

        h1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                h1KeyReleased(evt);
            }
        });
        getContentPane().add(h1);
        h1.setBounds(890, 120, 190, 50);

        jLabel15.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel15.setText("Customer Name");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(30, 190, 230, 30);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(320, 180, 190, 50);

        jLabel16.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel16.setText("New Due");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(560, 550, 230, 20);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(890, 550, 190, 50);
        getContentPane().add(b);
        b.setBounds(320, 420, 190, 50);
        getContentPane().add(i1);
        i1.setBounds(890, 310, 190, 50);

        jLabel17.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel17.setText("Customer ID");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(30, 140, 190, 30);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(320, 120, 190, 50);

        jLabel20.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel20.setText("Sub Category");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(30, 380, 210, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(320, 360, 190, 50);

        jLabel19.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel19.setText("Sale_ID");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(30, 80, 150, 30);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(320, 60, 190, 50);

        setSize(new java.awt.Dimension(1130, 752));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        a.setText("  ");
       
        c.setText("  ");
        d.setText("  ");
        e.setText("  ");
        f.setText("  ");
        g.setText("  ");
        h1.setText("  ");
        
        j.setText("  ");
        k.setText("  ");
        i.setText("  ");
        ac.setSelectedIndex(0);
              jComboBox1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            // TODO add your handling code here:
               Connection conn;
         PreparedStatement pst;
          SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
        String xyz=sdf.format(b.getDate());
         String mno=sdf.format(i1.getDate());
         
         try{
             Class.forName("com.mysql.jdbc.Driver");
             
             conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/mis","root","");
             String sql;
             
              sql = "Insert into sales(Sale_Id,Customer_Id,Customer_Name,Product,Category,Sub_Category,Invoice_No,Product_Amt,No_of_Entry,Date_of_Entry,Date_of_Invoice,Dispatched_Through,Quantity,Dispatched_Quantity,Remaining_Quantity,Gate_Pass_No,Material_outward_no,New_Due) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
              
                 pst = conn.prepareStatement(sql);
                  pst.setString(1,jTextField4.getText());
                 pst.setString(2,jTextField3.getText());
                 pst.setString(3,jTextField1.getText());
                 pst.setString(4,c.getText());
                 pst.setString(5,ac.getSelectedItem().toString());
                  pst.setString(6,jComboBox1.getSelectedItem().toString());
                 pst.setString(7,d.getText());
                 
                 pst.setString(8,e.getText());
                 pst.setString(9,a.getText());
                 pst.setString(10,xyz);
                 pst.setString(11,mno);
                 pst.setString(12,f.getText());
                 pst.setString(13,h1.getText());
                 pst.setString(14,i.getText());
                 pst.setString(15,g.getText());
                 pst.setString(16,j.getText());
                 pst.setString(17,k.getText());
                 pst.setString(18,jTextField2.getText());
               
                 
                       
              pst.execute();
              
              JOptionPane.showMessageDialog(null,"saved");
            }
         catch(Exception e)
         {
              JOptionPane.showMessageDialog(null, "PLEASE CHECK THE FIELDS AGAIN");
                       
          }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void aKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aKeyReleased
        // TODO add your handling code here:
        
int key=evt.getKeyCode();
    if(key==10)
    {
    b.requestFocus();
    }

    }//GEN-LAST:event_aKeyReleased

    private void acKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_acKeyReleased
        // TODO add your handling code here:
int key=evt.getKeyCode();
    if(key==10)
    {
    c.requestFocus();// TODO add your handling code here:
    }

    }//GEN-LAST:event_acKeyReleased

    private void cKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cKeyReleased
        // TODO add your handling code here:
        int key=evt.getKeyCode();
    if(key==10)
    {
    d.requestFocus();// TODO add your handling code here:
    }
    }//GEN-LAST:event_cKeyReleased

    private void dKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dKeyReleased
        // TODO add your handling code here:
        int key=evt.getKeyCode();
    if(key==10)
    {
    e.requestFocus();// TODO add your handling code here:
    }

    }//GEN-LAST:event_dKeyReleased

    private void eKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_eKeyReleased
        // TODO add your handling code here:
        int key=evt.getKeyCode();
    if(key==10)
    {
    f.requestFocus();// TODO add your handling code here:
    }
    }//GEN-LAST:event_eKeyReleased

    private void fKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fKeyReleased
        // TODO add your handling code here:
        int key=evt.getKeyCode();
    if(key==10)
    {
    g.requestFocus();// TODO add your handling code here:
    }

    }//GEN-LAST:event_fKeyReleased

    private void gKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gKeyReleased
        // TODO add your handling code here:
        int key=evt.getKeyCode();
    if(key==10)
    {
    h1.requestFocus();// TODO add your handling code here:
    }

    }//GEN-LAST:event_gKeyReleased

    private void h1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_h1KeyReleased
        // TODO add your handling code here:
        int key=evt.getKeyCode();
    if(key==10)
    {
    i1.requestFocus();// TODO add your handling code here:
    }

    }//GEN-LAST:event_h1KeyReleased

    private void iKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_iKeyReleased
        // TODO add your handling code here:
        int key=evt.getKeyCode();
    if(key==10)
    {
    j.requestFocus();// TODO add your handling code here:
    }

    }//GEN-LAST:event_iKeyReleased

    private void jKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jKeyReleased
        // TODO add your handling code here:
        int key=evt.getKeyCode();
    if(key==10)
    {
    k.requestFocus();// TODO add your handling code here:
    }

    }//GEN-LAST:event_jKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addsale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addsale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addsale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addsale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addsale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a;
    private javax.swing.JComboBox<String> ac;
    private com.toedter.calendar.JDateChooser b;
    private javax.swing.JTextField c;
    private javax.swing.JTextField d;
    private javax.swing.JTextField e;
    private javax.swing.JTextField f;
    private javax.swing.JTextField g;
    private javax.swing.JTextField h;
    private javax.swing.JTextField h1;
    private javax.swing.JTextField i;
    private com.toedter.calendar.JDateChooser i1;
    private javax.swing.JTextField j;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField k;
    // End of variables declaration//GEN-END:variables
}
