/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgfinal.java;

import com.mysql.jdbc.PreparedStatement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.sql.*;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;

/**
 *
 * @author DELL
 */
public class addyourproduct extends javax.swing.JFrame {

    /**
     * Creates new form addyourproduct
     */
    public addyourproduct() {
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        ac = new javax.swing.JComboBox<>();
        bc = new javax.swing.JComboBox<>();
        title = new javax.swing.JTextField();
        dealerprice = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        singleuserprice = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        remark = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        add_product = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel8.setText("Add Your Product");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(12, 13, 225, 42);

        ac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));
        ac.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                acKeyReleased(evt);
            }
        });
        getContentPane().add(ac);
        ac.setBounds(430, 140, 316, 40);

        bc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));
        bc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                bcKeyReleased(evt);
            }
        });
        getContentPane().add(bc);
        bc.setBounds(430, 200, 316, 40);

        title.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                titleKeyReleased(evt);
            }
        });
        getContentPane().add(title);
        title.setBounds(430, 80, 316, 40);

        dealerprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dealerpriceActionPerformed(evt);
            }
        });
        dealerprice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dealerpriceKeyReleased(evt);
            }
        });
        getContentPane().add(dealerprice);
        dealerprice.setBounds(430, 340, 316, 40);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setText("Category");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 150, 230, 30);

        singleuserprice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                singleuserpriceKeyReleased(evt);
            }
        });
        getContentPane().add(singleuserprice);
        singleuserprice.setBounds(430, 410, 316, 40);

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel2.setText("Sub- Category");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 210, 260, 30);
        getContentPane().add(remark);
        remark.setBounds(430, 470, 316, 84);

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel3.setText("Title");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 90, 220, 30);

        add_product.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        add_product.setText("Add Product");
        add_product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_productActionPerformed(evt);
            }
        });
        getContentPane().add(add_product);
        add_product.setBounds(340, 590, 130, 40);

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel4.setText("Dealer Price");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 350, 230, 30);

        jButton2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(480, 590, 130, 40);

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel5.setText("Single User Price");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 420, 290, 30);

        jButton3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(620, 590, 130, 40);

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel6.setText("Remarks");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 500, 170, 30);

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel9.setText("Quantity ");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(80, 280, 210, 30);

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(430, 270, 310, 40);

        setSize(new java.awt.Dimension(864, 695));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dealerpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dealerpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dealerpriceActionPerformed

    private void add_productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_productActionPerformed
     Connection conn;
        java.sql.PreparedStatement pst = null;
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/mis","root","");
            String sql;
            sql = "Insert into product(Title,Category,Sub_Category,Quantity,Dealer_Price,Single_User_Price,Remarks) values (?,?,?,?,?,?,?)";
            
            pst = conn.prepareStatement(sql);
            
             pst.setString(1,title.getText());
            pst.setString(2,ac.getSelectedItem().toString());
            pst.setString(3,bc.getSelectedItem().toString());
            pst.setString(4,jTextField1.getText());
            pst.setString(5,dealerprice.getText());
            pst.setString(6,singleuserprice.getText());
            pst.setString(7,remark.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "saved");
        }
        catch(Exception e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "PLEASE CHECK THE FIELDS AGAIN");
        }
    }//GEN-LAST:event_add_productActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        title.setText("  ");
        dealerprice.setText("  ");
        singleuserprice.setText("  ");
        remark.setText("   ");
        ac.setSelectedIndex(0);
        bc.setSelectedIndex(0);
        jTextField1.setText(" ");
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void acKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_acKeyReleased
        // TODO add your handling code here:
        int key=evt.getKeyCode();
    if(key==10)
    {
    bc.requestFocus();// TODO add your handling code here:
    }

    }//GEN-LAST:event_acKeyReleased

    private void bcKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bcKeyReleased
        // TODO add your handling code here:
        int key=evt.getKeyCode();
    if(key==10)
    {
    jTextField1.requestFocus();// TODO add your handling code here:
    }

    }//GEN-LAST:event_bcKeyReleased

    private void titleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_titleKeyReleased
        // TODO add your handling code here:
        int key=evt.getKeyCode();
    if(key==10)
    {
    ac.requestFocus();// TODO add your handling code here:
    }

    }//GEN-LAST:event_titleKeyReleased

    private void dealerpriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dealerpriceKeyReleased
        // TODO add your handling code here:
        int key=evt.getKeyCode();
    if(key==10)
    {
    singleuserprice.requestFocus();// TODO add your handling code here:
    }

    }//GEN-LAST:event_dealerpriceKeyReleased

    private void singleuserpriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_singleuserpriceKeyReleased
        // TODO add your handling code here:
        int key=evt.getKeyCode();
    if(key==10)
    {
    remark.requestFocus();// TODO add your handling code here:
    }

    }//GEN-LAST:event_singleuserpriceKeyReleased

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
          int key=evt.getKeyCode();
    if(key==10)
    {
    dealerprice.requestFocus();// TODO add your handling code here:
    }
    }//GEN-LAST:event_jTextField1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addyourproduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addyourproduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addyourproduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addyourproduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addyourproduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ac;
    private javax.swing.JButton add_product;
    private javax.swing.JComboBox<String> bc;
    private javax.swing.JTextField dealerprice;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField remark;
    private javax.swing.JTextField singleuserprice;
    private javax.swing.JTextField title;
    // End of variables declaration//GEN-END:variables
}
