/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgfinal.java;

import java.awt.HeadlessException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.*;
import javax.swing.*;

import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import java.sql.Connection; 
import java.sql.DriverManager; 
import java.sql.ResultSet; 
import java.sql.Statement;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;


/**
 *
 * @author DELL
 */
public class amccustomer extends javax.swing.JFrame {
    Connection conn=null;
        ResultSet rs=null;
        PreparedStatement pst=null;

    /**
     * Creates new form amccustomer
     */
    public amccustomer() {
        initComponents();
         view_table();
    }
    
       private void view_table(){
    try{
        conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/mis","root","");
        String sql;
        sql="select * from customer where Status='Under AMC'";
        pst=conn.prepareStatement(sql);
        rs=pst.executeQuery();
        tb.setModel(DbUtils.resultSetToTableModel(rs));;
    }
    catch(Exception e)
    {
        JOptionPane.showMessageDialog(null,e);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tb = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "CUSTOMER", "ORGANISATION", "PHONE", "INVOICE", "SALE_DATE", "LOCATION", "PRODUCT", "SERIAL", "STATUS", "EXPIRE_DATE"
            }
        ));
        jScrollPane1.setViewportView(tb);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(11, 44, 1170, 256);

        jButton3.setText("Export");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(337, 332, 65, 23);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(482, 332, 55, 23);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setText("List of Warrenty Customers");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(474, 6, 280, 30);

        setSize(new java.awt.Dimension(1211, 494));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
          int r = 1;
        String a[]=new String[100];
        
        Workbook wb = new HSSFWorkbook();
        Sheet sheet = wb.createSheet("Customer Under AMC");
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/customer","root","");
            String sql;
            sql="select * from customer where Status='Under AMC'";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            Row row;
            int i=0;
            
            
            // heading
                row=sheet.createRow(0);
                Cell cell = row.createCell(0);
                cell.setCellValue("Customer_Id");
                cell = row.createCell(1);
                cell.setCellValue("Sl");
                cell = row.createCell(2);
                cell.setCellValue("Name");
                cell = row.createCell(3);
                cell.setCellValue("Organisation");
                cell = row.createCell(4);
                cell.setCellValue("Phone");
                cell = row.createCell(5);
                cell.setCellValue("Invoice");
                cell = row.createCell(6);
                cell.setCellValue("Date");
                cell = row.createCell(7);
                cell.setCellValue("Location");
                cell = row.createCell(8);
                cell.setCellValue("Product");
                cell = row.createCell(9);
                cell.setCellValue("Email");
                cell = row.createCell(10);
                cell.setCellValue("Status");
                cell = row.createCell(11);
                cell.setCellValue("Status_for");
            //data
                r=1;
                while(rs.next()) {
                    String d1 = rs.getString("Customer_Id");
                    String d2 = rs.getString("Sl");
                    String d3 = rs.getString("Name");
                    String d4 = rs.getString("Organisation");
                    String d5 = rs.getString("Phone");
                    String d6 = rs.getString("Invoice");
                    String d7 = rs.getString("Date");
                    String d8 = rs.getString("Location");
                    String d9 = rs.getString("Product");
                    String d10 = rs.getString("Email");
                    String d11= rs.getString("Status");
                    String d12= rs.getString("Status_for");
                    row= sheet.createRow(r);
                    cell = row.createCell(0);
                    cell.setCellValue(d1);
                    cell = row.createCell(1);
                    cell.setCellValue(d2);
                    cell = row.createCell(2);
                    cell.setCellValue(d3);
                    cell = row.createCell(3);
                    cell.setCellValue(d4);
                    cell = row.createCell(4);
                    cell.setCellValue(d5);
                    cell = row.createCell(5);
                    cell.setCellValue(d6);
                    cell = row.createCell(6);
                    cell.setCellValue(d7);
                    cell = row.createCell(7);
                    cell.setCellValue(d8);
                    cell = row.createCell(8);
                    cell.setCellValue(d9);
                    cell = row.createCell(9);
                    cell.setCellValue(d10);
                    cell = row.createCell(10);
                    cell.setCellValue(d11);
                    cell = row.createCell(11);
                    cell.setCellValue(d12);
                    r++;
             }
            try
        {
            //Write the workbook in file system
            String outdir="E:/CustomerUnderAMC.xls";
                try (FileOutputStream out = new FileOutputStream(outdir)) {
                    wb.write(out);
                     JOptionPane.showMessageDialog(null,"Exported");
                }
        }
        catch (IOException e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        }
        catch(HeadlessException | ClassNotFoundException | SQLException e)
        {
             JOptionPane.showMessageDialog(null,"PLEASE INSERT EXTERNAL STORAGE");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(amccustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(amccustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(amccustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(amccustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new amccustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb;
    // End of variables declaration//GEN-END:variables
}
