/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgfinal.java;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.io.*;
import org.apache.poi.ss.usermodel.*;
import java.util.*;
import org.apache.poi.xssf.usermodel.*;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.openxml4j.exceptions.InvalidFormatException;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.ss.usermodel.WorkbookFactory;

/**
 *
 * @author DELL
 */
public class resetexport extends javax.swing.JFrame {
     Connection conn=null;
        ResultSet rs=null;
        PreparedStatement pst=null;
    /**
     * Creates new form resetexport
     */
    public resetexport() {
        initComponents();
        jButton1.setVisible(false);
        jButton3.setVisible(false);
        jButton4.setVisible(false);
        jButton5.setVisible(false);
        jButton6.setVisible(false);
        jButton7.setVisible(false);
        jButton8.setVisible(false);
        jButton9.setVisible(false);
        jButton10.setVisible(false);
        jButton11.setVisible(false);
        jButton12.setVisible(false);
        jButton13.setVisible(false);
        jButton16.setVisible(false);
        jButton15.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("RESET");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(21, 26, 147, 45);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setText("RESET CHANNEL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(21, 98, 147, 40);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton3.setText("RESET CUSTOMER");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(21, 145, 147, 40);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton4.setText("RESET PRODUCT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(21, 192, 147, 40);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton5.setText("RESET PURCHASE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(21, 239, 147, 40);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton6.setText("RESET COMPLAINT");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(21, 286, 147, 40);

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton7.setText("RESET ENQUIRY");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(21, 333, 147, 40);

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton8.setText("RESET SALES");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(21, 380, 147, 40);

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton9.setText("EXPORT PRODUCT");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(425, 192, 159, 40);

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton10.setText("EXPORT PURCHASE");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(425, 239, 159, 40);

        jButton11.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton11.setText("EXPORT COMPLAINT");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(425, 286, 159, 40);

        jButton12.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton12.setText("EXPORT ENQUIRY");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12);
        jButton12.setBounds(425, 333, 159, 40);

        jButton13.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton13.setText("EXPORT SALES");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13);
        jButton13.setBounds(425, 380, 159, 40);

        jButton14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton14.setText("EXPORT");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton14);
        jButton14.setBounds(425, 26, 159, 45);

        jButton15.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton15.setText("EXPORT CHANNEL");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton15);
        jButton15.setBounds(425, 98, 159, 40);

        jButton16.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton16.setText("EXPORT CUSTOMER");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton16);
        jButton16.setBounds(425, 145, 159, 40);

        jButton17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton17.setText("CANCEL");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton17);
        jButton17.setBounds(655, 474, 108, 39);

        setSize(new java.awt.Dimension(814, 655));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
           try
        {
            Class.forName("com.mysql.jdbc.Driver");
            
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/mis","root","");
            
            String sql;
            sql="TRUNCATE channel";
             pst=conn.prepareStatement(sql);
            pst.execute();
            
            JOptionPane.showMessageDialog(null,"truncated");
        }
        
        catch(Exception e)
        {
             JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jButton1.setVisible(true);
        jButton3.setVisible(true);
        jButton4.setVisible(true);
        jButton5.setVisible(true);
        jButton6.setVisible(true);
        jButton7.setVisible(true);
        jButton8.setVisible(true);
        jButton9.setVisible(false);
        jButton10.setVisible(false);
        jButton11.setVisible(false);
        jButton12.setVisible(false);
        jButton13.setVisible(false);
        jButton16.setVisible(false);
        jButton15.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        jButton9.setVisible(true);
        jButton10.setVisible(true);
        jButton11.setVisible(true);
        jButton12.setVisible(true);
        jButton13.setVisible(true);
        jButton16.setVisible(true);
        jButton15.setVisible(true);
        jButton1.setVisible(false);
        jButton3.setVisible(false);
        jButton4.setVisible(false);
        jButton5.setVisible(false);
        jButton6.setVisible(false);
        jButton7.setVisible(false);
        jButton8.setVisible(false);
        
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
            try
        {
            Class.forName("com.mysql.jdbc.Driver");
            
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/mis","root","");
            
            String sql;
            sql="TRUNCATE purchase";
             pst=conn.prepareStatement(sql);
            pst.execute();
            
            JOptionPane.showMessageDialog(null,"truncated");
        }
        
        catch(Exception e)
        {
             JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/mis","root","");
            
            String sql;
            sql="TRUNCATE complaint";
             pst=conn.prepareStatement(sql);
            pst.execute();
            
            JOptionPane.showMessageDialog(null,"truncated");
        }
        
        catch(Exception e)
        {
             JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         try
        {
            Class.forName("com.mysql.jdbc.Driver");
            
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/mis","root","");
            
            String sql;
            sql="TRUNCATE product";
             pst=conn.prepareStatement(sql);
            pst.execute();
            
            JOptionPane.showMessageDialog(null,"truncated");
        }
        
        catch(Exception e)
        {
             JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
         try
        {
            Class.forName("com.mysql.jdbc.Driver");
            
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/mis","root","");
            
            String sql;
            sql="TRUNCATE enquiry";
             pst=conn.prepareStatement(sql);
            pst.execute();
            
            JOptionPane.showMessageDialog(null,"truncated");
        }
        
        catch(Exception e)
        {
             JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
          try
        {
            Class.forName("com.mysql.jdbc.Driver");
            
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/mis","root","");
            
            String sql;
            sql="TRUNCATE sales";
             pst=conn.prepareStatement(sql);
            pst.execute();
            
            JOptionPane.showMessageDialog(null,"truncated");
        }
        
        catch(Exception e)
        {
             JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         try
        {
            Class.forName("com.mysql.jdbc.Driver");
            
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/mis","root","");
            
            String sql;
            sql="TRUNCATE customer";
             pst=conn.prepareStatement(sql);
            pst.execute();
            
            JOptionPane.showMessageDialog(null,"truncated");
        }
        
        catch(Exception e)
        {
             JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        int r = 1;
        String a[]=new String[100];
        
        Workbook wb = new HSSFWorkbook();
        Sheet sheet = wb.createSheet("Customer");
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/mis","root","");
            String sql;
            sql="select * from customer";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            Row row;
            int i=0;
            
            
            // heading
                row=sheet.createRow(0);
                Cell cell = row.createCell(0);
                cell.setCellValue("Customer_Id");
                cell = row.createCell(1);
                cell.setCellValue("Sl");
                cell = row.createCell(2);
                cell.setCellValue("Name");
                cell = row.createCell(3);
                cell.setCellValue("Organisation");
                cell = row.createCell(4);
                cell.setCellValue("Phone");
                cell = row.createCell(5);
                cell.setCellValue("Invoice");
                cell = row.createCell(6);
                cell.setCellValue("Date");
                cell = row.createCell(7);
                cell.setCellValue("Location");
                cell = row.createCell(8);
                cell.setCellValue("Product");
                cell = row.createCell(9);
                cell.setCellValue("Email");
                cell = row.createCell(10);
                cell.setCellValue("Status");
                cell = row.createCell(11);
                cell.setCellValue("Status_for");
            //data
                r=1;
                while(rs.next()) {
                    String d1 = rs.getString("Customer_Id");
                    String d2 = rs.getString("Sl");
                    String d3 = rs.getString("Name");
                    String d4 = rs.getString("Organisation");
                    String d5 = rs.getString("Phone");
                    String d6 = rs.getString("Invoice");
                    String d7 = rs.getString("Date");
                    String d8 = rs.getString("Location");
                    String d9 = rs.getString("Product");
                    String d10 = rs.getString("Email");
                    String d11= rs.getString("Status");
                    String d12= rs.getString("Status_for");
                    row= sheet.createRow(r);
                    cell = row.createCell(0);
                    cell.setCellValue(d1);
                    cell = row.createCell(1);
                    cell.setCellValue(d2);
                    cell = row.createCell(2);
                    cell.setCellValue(d3);
                    cell = row.createCell(3);
                    cell.setCellValue(d4);
                    cell = row.createCell(4);
                    cell.setCellValue(d5);
                    cell = row.createCell(5);
                    cell.setCellValue(d6);
                    cell = row.createCell(6);
                    cell.setCellValue(d7);
                    cell = row.createCell(7);
                    cell.setCellValue(d8);
                    cell = row.createCell(8);
                    cell.setCellValue(d9);
                    cell = row.createCell(9);
                    cell.setCellValue(d10);
                    cell = row.createCell(10);
                    cell.setCellValue(d11);
                    cell = row.createCell(11);
                    cell.setCellValue(d12);
                    r++;
             }
            try
        {
            //Write the workbook in file system
            String outdir="E:/Customer.xls";
                try (FileOutputStream out = new FileOutputStream(outdir)) {
                    wb.write(out);
                     JOptionPane.showMessageDialog(null,"Exported");
                }
        }
        catch (IOException e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        }
        catch(HeadlessException | ClassNotFoundException | SQLException e)
        {
             JOptionPane.showMessageDialog(null,"PLEASE INSERT AN EXTERNAL STORAGE");
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
         int r = 1;
        String a[]=new String[100];
        
        Workbook wb = new HSSFWorkbook();
        Sheet sheet = wb.createSheet("Purchase");
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/mis","root","");
            String sql;
            sql="select * from purchase";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            Row row;
            int i=0;
            
            
            // heading
                row=sheet.createRow(0);
                Cell cell = row.createCell(0);
                cell.setCellValue("Customer_Id");
                cell = row.createCell(1);
                cell.setCellValue("Sl");
                cell = row.createCell(2);
                cell.setCellValue("Party Name");
                cell = row.createCell(3);
                cell.setCellValue("Particulars");
                cell = row.createCell(4);
                cell.setCellValue("Invoice");
                cell = row.createCell(5);
                cell.setCellValue("Product");
                cell = row.createCell(6);
                cell.setCellValue("Order Date");
                cell = row.createCell(7);
                cell.setCellValue("Amount");
                cell = row.createCell(8);
                cell.setCellValue("Recieve Date");
                cell = row.createCell(9);
                cell.setCellValue("Quantity");
                cell = row.createCell(10);
                cell.setCellValue("Quantity Recieved");
                cell = row.createCell(11);
                cell.setCellValue("Remaining Quantity");
                 cell = row.createCell(12);
                cell.setCellValue("Mi No");
                 cell = row.createCell(13);
                cell.setCellValue("Recieved By");
                 cell = row.createCell(14);
                cell.setCellValue("New Due");
            //data
                r=1;
                while(rs.next()) {
                    String d1 = rs.getString("Customer_Id");
                    String d2 = rs.getString("Sl");
                    String d3 = rs.getString("Party_Name");
                    String d4 = rs.getString("Particulars");
                    String d5 = rs.getString("Invoice");
                    String d6 = rs.getString("Product");
                    String d7 = rs.getString("Order_Date");
                    String d8 = rs.getString("Amount");
                    String d9 = rs.getString("Recieve_Date");
                    String d10 = rs.getString("Quantity");
                    String d11= rs.getString("Quantity_Recieved");
                    String d12= rs.getString("Remaining_Quantity");
                    String d13= rs.getString("Mi_No");
                    String d14= rs.getString("Recieved_By");
                    String d15= rs.getString("New_Due");
                    row= sheet.createRow(r);
                    cell = row.createCell(0);
                    cell.setCellValue(d1);
                    cell = row.createCell(1);
                    cell.setCellValue(d2);
                    cell = row.createCell(2);
                    cell.setCellValue(d3);
                    cell = row.createCell(3);
                    cell.setCellValue(d4);
                    cell = row.createCell(4);
                    cell.setCellValue(d5);
                    cell = row.createCell(5);
                    cell.setCellValue(d6);
                    cell = row.createCell(6);
                    cell.setCellValue(d7);
                    cell = row.createCell(7);
                    cell.setCellValue(d8);
                    cell = row.createCell(8);
                    cell.setCellValue(d9);
                    cell = row.createCell(9);
                    cell.setCellValue(d10);
                    cell = row.createCell(10);
                    cell.setCellValue(d11);
                    cell = row.createCell(11);
                    cell.setCellValue(d12);
                    cell = row.createCell(12);
                    cell.setCellValue(d13);
                    cell = row.createCell(13);
                    cell.setCellValue(d14);
                    cell = row.createCell(14);
                    cell.setCellValue(d15);
                    r++;
             }
            try
        {
            //Write the workbook in file system
            String outdir="E:/Purchase.xls";
                try (FileOutputStream out = new FileOutputStream(outdir)) {
                    wb.write(out);
                     JOptionPane.showMessageDialog(null,"Exported");
                }
        }
        catch (IOException e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        }
        catch(HeadlessException | ClassNotFoundException | SQLException e)
        {
             JOptionPane.showMessageDialog(null,"PLEASE INSERT AN EXTERNAL STORAGE");
        }
                                            
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
         int r = 1;
        String a[]=new String[100];
        
        Workbook wb = new HSSFWorkbook();
        Sheet sheet = wb.createSheet("Channel");
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/mis","root","");
            String sql;
            sql="select * from channel";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            Row row;
            int i=0;
            
            
            // heading
                row=sheet.createRow(0);
                Cell cell = row.createCell(0);
                cell.setCellValue("Name Of Channel");
                cell = row.createCell(1);
                cell.setCellValue("Phone Number");
                cell = row.createCell(2);
                cell.setCellValue("Mail");
                cell = row.createCell(3);
                cell.setCellValue("Location");
              
            //data
                r=1;
                while(rs.next()) {
                    String d1 = rs.getString("Name_of_Channel");
                    String d2 = rs.getString("Phone_No");
                    String d3 = rs.getString("Mail");
                    String d4 = rs.getString("Location");
                   
                    row= sheet.createRow(r);
                    cell = row.createCell(0);
                    cell.setCellValue(d1);
                    cell = row.createCell(1);
                    cell.setCellValue(d2);
                    cell = row.createCell(2);
                    cell.setCellValue(d3);
                    cell = row.createCell(3);
                    cell.setCellValue(d4);
                  
                    r++;
             }
            try
        {
            //Write the workbook in file system
            String outdir="E:/Channel.xls";
                try (FileOutputStream out = new FileOutputStream(outdir)) {
                    wb.write(out);
                     JOptionPane.showMessageDialog(null,"Exported");
                }
        }
        catch (IOException e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        }
        catch(HeadlessException | ClassNotFoundException | SQLException e)
        {
             JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
         int r = 1;
        String a[]=new String[100];
        
        Workbook wb = new HSSFWorkbook();
        Sheet sheet = wb.createSheet("Product");
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/mis","root","");
            String sql;
            sql="select * from product";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            Row row;
            int i=0;
            
            
            // heading
                row=sheet.createRow(0);
                Cell cell = row.createCell(0);
                cell.setCellValue("Category");
                cell = row.createCell(1);
                cell.setCellValue("Sub Category");
                cell = row.createCell(2);
                cell.setCellValue("Title");
                cell = row.createCell(3);
                cell.setCellValue("Dealer Price");
                cell = row.createCell(4);
                cell.setCellValue("Single User Price");
                cell = row.createCell(5);
                cell.setCellValue("Remarks");
               
            //data
                r=1;
                while(rs.next()) {
                    String d1 = rs.getString("Category");
                    String d2 = rs.getString("Sub_Category");
                    String d3 = rs.getString("Title");
                    String d4 = rs.getString("Dealer_Price");
                    String d5 = rs.getString("Single_User_Price");
                    String d6 = rs.getString("Remarks");
                   
                    row= sheet.createRow(r);
                    cell = row.createCell(0);
                    cell.setCellValue(d1);
                    cell = row.createCell(1);
                    cell.setCellValue(d2);
                    cell = row.createCell(2);
                    cell.setCellValue(d3);
                    cell = row.createCell(3);
                    cell.setCellValue(d4);
                    cell = row.createCell(4);
                    cell.setCellValue(d5);
                    cell = row.createCell(5);
                    cell.setCellValue(d6);
                   
                    r++;
             }
            try
        {
            //Write the workbook in file system
            String outdir="E:/Product.xls";
                try (FileOutputStream out = new FileOutputStream(outdir)) {
                    wb.write(out);
                     JOptionPane.showMessageDialog(null,"Exported");
                }
        }
        catch (IOException e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        }
        catch(HeadlessException | ClassNotFoundException | SQLException e)
        {
             JOptionPane.showMessageDialog(null,"PLEASE INSERT AN EXTERNAL STORAGE");
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
         int r = 1;
        String a[]=new String[100];
        
        Workbook wb = new HSSFWorkbook();
        Sheet sheet = wb.createSheet("Purchase");
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/mis","root","");
            String sql;
            sql="select * from complaint";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            Row row;
            int i=0;
            
            
            // heading
                row=sheet.createRow(0);
                Cell cell = row.createCell(0);
                cell.setCellValue("Customer_Id");
                cell = row.createCell(1);
                cell.setCellValue("Sl");
                cell = row.createCell(2);
                cell.setCellValue("Customer");
                cell = row.createCell(3);
                cell.setCellValue("City");
                cell = row.createCell(4);
                cell.setCellValue("Location");
                cell = row.createCell(5);
                cell.setCellValue("Phone");
                cell = row.createCell(6);
                cell.setCellValue("Other Contact");
                cell = row.createCell(7);
                cell.setCellValue("Email");
                cell = row.createCell(8);
                cell.setCellValue("Category");
                cell = row.createCell(9);
                cell.setCellValue("Sub Category");
                cell = row.createCell(10);
                cell.setCellValue("Date");
                cell = row.createCell(11);
                cell.setCellValue("Product");
                 cell = row.createCell(12);
                cell.setCellValue("Problem");
                 cell = row.createCell(13);
                cell.setCellValue("Remarks");
                 cell = row.createCell(14);
                cell.setCellValue("Product Under");
                cell = row.createCell(15);
                cell.setCellValue("Solved By");
            //data
                r=1;
                while(rs.next()) {
                    String d1 = rs.getString("Customer_Id");
                    String d2 = rs.getString("Sl");
                    String d3 = rs.getString("Customer");
                    String d4 = rs.getString("City");
                    String d5 = rs.getString("Location");
                    String d6 = rs.getString("Phone");
                    String d7 = rs.getString("Other_Contact");
                    String d8 = rs.getString("Email");
                    String d9 = rs.getString("Category");
                    String d10 = rs.getString("Sub_Category");
                    String d11= rs.getString("Date");
                    String d12= rs.getString("Product");
                    String d13= rs.getString("Problem");
                    String d14= rs.getString("Remarks");
                    String d15= rs.getString("Product_Under");
                    String d16= rs.getString("Solved_By");
                    row= sheet.createRow(r);
                    cell = row.createCell(0);
                    cell.setCellValue(d1);
                    cell = row.createCell(1);
                    cell.setCellValue(d2);
                    cell = row.createCell(2);
                    cell.setCellValue(d3);
                    cell = row.createCell(3);
                    cell.setCellValue(d4);
                    cell = row.createCell(4);
                    cell.setCellValue(d5);
                    cell = row.createCell(5);
                    cell.setCellValue(d6);
                    cell = row.createCell(6);
                    cell.setCellValue(d7);
                    cell = row.createCell(7);
                    cell.setCellValue(d8);
                    cell = row.createCell(8);
                    cell.setCellValue(d9);
                    cell = row.createCell(9);
                    cell.setCellValue(d10);
                    cell = row.createCell(10);
                    cell.setCellValue(d11);
                    cell = row.createCell(11);
                    cell.setCellValue(d12);
                    cell = row.createCell(12);
                    cell.setCellValue(d13);
                    cell = row.createCell(13);
                    cell.setCellValue(d14);
                    cell = row.createCell(14);
                    cell.setCellValue(d15);
                    cell = row.createCell(15);
                    cell.setCellValue(d16);
                    r++;
             }
            try
        {
            //Write the workbook in file system
            String outdir="E:/Complaint.xls";
                try (FileOutputStream out = new FileOutputStream(outdir)) {
                    wb.write(out);
                     JOptionPane.showMessageDialog(null,"Exported");
                }
        }
        catch (IOException e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        }
        catch(HeadlessException | ClassNotFoundException | SQLException e)
        {
             JOptionPane.showMessageDialog(null,"PLEASE INSERT AN EXTERNAL STORAGE");
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        int r = 1;
        String a[]=new String[100];
        
        Workbook wb = new HSSFWorkbook();
        Sheet sheet = wb.createSheet("Enquiry");
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/mis","root","");
            String sql;
            sql="select * from enquiry";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            Row row;
            int i=0;
            
            
            // heading
                row=sheet.createRow(0);
                Cell cell = row.createCell(0);
                cell.setCellValue("Customer_Id");
                cell = row.createCell(1);
                cell.setCellValue("Name");
                cell = row.createCell(2);
                cell.setCellValue("Company");
                cell = row.createCell(3);
                cell.setCellValue("City");
                cell = row.createCell(4);
                cell.setCellValue("Location");
                cell = row.createCell(5);
                cell.setCellValue("Address");
                cell = row.createCell(6);
                cell.setCellValue("Email");
                cell = row.createCell(7);
                cell.setCellValue("Phone");
                cell = row.createCell(8);
                cell.setCellValue("Other Contact");
                cell = row.createCell(9);
                cell.setCellValue("Category");
                cell = row.createCell(10);
                cell.setCellValue("Sub Category");
                cell = row.createCell(11);
                cell.setCellValue("Product");
                 cell = row.createCell(12);
                cell.setCellValue("Customer Type");
                 cell = row.createCell(13);
                cell.setCellValue("Enquiry Type");
                 cell = row.createCell(14);
                cell.setCellValue("Sources");
                cell = row.createCell(15);
                cell.setCellValue("Date");
                cell = row.createCell(16);
                cell.setCellValue("Remarks");
            //data
                r=1;
                while(rs.next()) {
                    String d1 = rs.getString("Customer_Id");
                    String d2 = rs.getString("Name");
                    String d3 = rs.getString("Company");
                    String d4 = rs.getString("City");
                    String d5 = rs.getString("Location");
                    String d6 = rs.getString("Address");
                    String d7 = rs.getString("Email");
                    String d8 = rs.getString("Phone");
                    String d9 = rs.getString("Other_Contact");
                    String d10 = rs.getString("Category");
                    String d11= rs.getString("Sub_Category");
                    String d12= rs.getString("Product");
                    String d13= rs.getString("Customer_Type");
                    String d14= rs.getString("Enquiry_Type");
                    String d15= rs.getString("Sources");
                    String d16= rs.getString("Date");
                    String d17= rs.getString("Remarks");
                    row= sheet.createRow(r);
                    cell = row.createCell(0);
                    cell.setCellValue(d1);
                    cell = row.createCell(1);
                    cell.setCellValue(d2);
                    cell = row.createCell(2);
                    cell.setCellValue(d3);
                    cell = row.createCell(3);
                    cell.setCellValue(d4);
                    cell = row.createCell(4);
                    cell.setCellValue(d5);
                    cell = row.createCell(5);
                    cell.setCellValue(d6);
                    cell = row.createCell(6);
                    cell.setCellValue(d7);
                    cell = row.createCell(7);
                    cell.setCellValue(d8);
                    cell = row.createCell(8);
                    cell.setCellValue(d9);
                    cell = row.createCell(9);
                    cell.setCellValue(d10);
                    cell = row.createCell(10);
                    cell.setCellValue(d11);
                    cell = row.createCell(11);
                    cell.setCellValue(d12);
                    cell = row.createCell(12);
                    cell.setCellValue(d13);
                    cell = row.createCell(13);
                    cell.setCellValue(d14);
                    cell = row.createCell(14);
                    cell.setCellValue(d15);
                    cell = row.createCell(15);
                    cell.setCellValue(d16);
                    cell = row.createCell(16);
                    cell.setCellValue(d17);
                    r++;
             }
            try
        {
            //Write the workbook in file system
            String outdir="E:/Enquiry.xls";
                try (FileOutputStream out = new FileOutputStream(outdir)) {
                    wb.write(out);
                     JOptionPane.showMessageDialog(null,"Exported");
                }
        }
        catch (IOException e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        }
        catch(HeadlessException | ClassNotFoundException | SQLException e)
        {
             JOptionPane.showMessageDialog(null,"PLEASE INSERT AN EXTERNAL STORAGE");
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
          int r = 1;
        String a[]=new String[100];
        
        Workbook wb = new HSSFWorkbook();
        Sheet sheet = wb.createSheet("Sales");
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/mis","root","");
            String sql;
            sql="select * from sales";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            Row row;
            int i=0;
            
            
            // heading
                row=sheet.createRow(0);
                Cell cell = row.createCell(0);
                cell.setCellValue("Customer_Id");
                cell = row.createCell(1);
                cell.setCellValue("Customer Name");
                cell = row.createCell(2);
                cell.setCellValue("Particulars");
                cell = row.createCell(3);
                cell.setCellValue("Invoice No");
                cell = row.createCell(4);
                cell.setCellValue("Product");
                cell = row.createCell(5);
                cell.setCellValue("Product_Amount");
                cell = row.createCell(6);
                cell.setCellValue("No Of Entry");
                cell = row.createCell(7);
                cell.setCellValue("Date Of Entry");
                cell = row.createCell(8);
                cell.setCellValue("Date Of Invoice");
                cell = row.createCell(9);
                cell.setCellValue("Dispatched Through");
                cell = row.createCell(10);
                cell.setCellValue("Quantity");
                cell = row.createCell(11);
                cell.setCellValue("Dispatched Quantity");
                 cell = row.createCell(12);
                cell.setCellValue("Remaining Quantity");
                 cell = row.createCell(13);
                cell.setCellValue("Gate Pass No");
                 cell = row.createCell(14);
                cell.setCellValue("Material Outward No");
                cell = row.createCell(15);
                cell.setCellValue("New Due");
            //data
                r=1;
                while(rs.next()) {
                    String d1 = rs.getString("Customer_Id");
                    String d2 = rs.getString("Customer_Name");
                    String d3 = rs.getString("Particulars");
                    String d4 = rs.getString("Invoice_No");
                    String d5 = rs.getString("Product");
                    String d6 = rs.getString("Product_Amt");
                    String d7 = rs.getString("No_of_Entry");
                    String d8 = rs.getString("Date_of_Entry");
                    String d9 = rs.getString("Date_of_Invoice");
                    String d10 = rs.getString("Dispatched_Through");
                    String d11= rs.getString("Quantity");
                    String d12= rs.getString("Dispatched_Quantity");
                    String d13= rs.getString("Remaining_Quantity");
                    String d14= rs.getString("Gate_Pass_No");
                    String d15= rs.getString("Material_Outward_no");
                    String d16= rs.getString("New_Due");
                    row= sheet.createRow(r);
                    cell = row.createCell(0);
                    cell.setCellValue(d1);
                    cell = row.createCell(1);
                    cell.setCellValue(d2);
                    cell = row.createCell(2);
                    cell.setCellValue(d3);
                    cell = row.createCell(3);
                    cell.setCellValue(d4);
                    cell = row.createCell(4);
                    cell.setCellValue(d5);
                    cell = row.createCell(5);
                    cell.setCellValue(d6);
                    cell = row.createCell(6);
                    cell.setCellValue(d7);
                    cell = row.createCell(7);
                    cell.setCellValue(d8);
                    cell = row.createCell(8);
                    cell.setCellValue(d9);
                    cell = row.createCell(9);
                    cell.setCellValue(d10);
                    cell = row.createCell(10);
                    cell.setCellValue(d11);
                    cell = row.createCell(11);
                    cell.setCellValue(d12);
                    cell = row.createCell(12);
                    cell.setCellValue(d13);
                    cell = row.createCell(13);
                    cell.setCellValue(d14);
                    cell = row.createCell(14);
                    cell.setCellValue(d15);
                    cell = row.createCell(15);
                    cell.setCellValue(d16);
                    r++;
             }
            try
        {
            //Write the workbook in file system
            String outdir="E:/Sales.xls";
                try (FileOutputStream out = new FileOutputStream(outdir)) {
                    wb.write(out);
                     JOptionPane.showMessageDialog(null,"Exported");
                }
        }
        catch (IOException e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        }
        catch(HeadlessException | ClassNotFoundException | SQLException e)
        {
             JOptionPane.showMessageDialog(null,"PLEASE INSERT AN EXTERNAL STORAGE");
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(resetexport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(resetexport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(resetexport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(resetexport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new resetexport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    // End of variables declaration//GEN-END:variables
}
