/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgfinal.java;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class updatepurchase extends javax.swing.JFrame {
    Connection conn=null;
        ResultSet rs=null;
        PreparedStatement pst=null;
    static String bb1,bb2,bb3,bb4,bb5,bb,bb6,bb7,bb8,bb9,bb10,bb11,bb12,bb13,bb14,bb15;

    /**
     * Creates new form updatepurchase
     */
    public updatepurchase() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        product = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        quantities = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        invoiceno = new javax.swing.JTextField();
        invoiceamnt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        mino = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        qtyreceived = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        serialno = new javax.swing.JTextField();
        remainingqnty = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        receivedby = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ae = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        ac = new javax.swing.JTextField();
        dateofentry = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton3.setText("CANCEL");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(650, 627, 81, 72);

        product.setColumns(20);
        product.setRows(5);
        product.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        product.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                productKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(product);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(240, 430, 230, 58);

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setText("Quantity");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(510, 190, 160, 23);

        quantities.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                quantitiesKeyReleased(evt);
            }
        });
        getContentPane().add(quantities);
        quantities.setBounds(750, 190, 180, 20);

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel7.setText("Invoice No.");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 530, 160, 23);

        jLabel13.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel13.setText("Received By");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(510, 560, 210, 23);

        invoiceno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                invoicenoKeyReleased(evt);
            }
        });
        getContentPane().add(invoiceno);
        invoiceno.setBounds(240, 530, 230, 20);

        invoiceamnt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                invoiceamntKeyReleased(evt);
            }
        });
        getContentPane().add(invoiceamnt);
        invoiceamnt.setBounds(750, 250, 180, 20);

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel8.setText("Invoice Amount");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(510, 250, 200, 23);

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel9.setText("Date Received");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(510, 310, 200, 23);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("UPDATE PURCHASE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(23, 22, 300, 45);

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel10.setText("MI No.");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(510, 380, 150, 23);

        mino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                minoKeyReleased(evt);
            }
        });
        getContentPane().add(mino);
        mino.setBounds(750, 370, 190, 20);

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel11.setText("Qty. Received");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(510, 440, 200, 23);

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel2.setText("Serial No.");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(26, 256, 160, 23);

        qtyreceived.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qtyreceivedKeyReleased(evt);
            }
        });
        getContentPane().add(qtyreceived);
        qtyreceived.setBounds(750, 440, 190, 20);

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel12.setText("Remaining Qty");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(510, 500, 210, 23);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Party Name");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(25, 189, 160, 20);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(240, 180, 230, 20);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("New Due");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(30, 580, 150, 20);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(240, 580, 230, 20);

        serialno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                serialnoKeyReleased(evt);
            }
        });
        getContentPane().add(serialno);
        serialno.setBounds(240, 250, 230, 20);

        remainingqnty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                remainingqntyKeyReleased(evt);
            }
        });
        getContentPane().add(remainingqnty);
        remainingqnty.setBounds(750, 500, 190, 20);

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setText("Date Ordered");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(25, 317, 170, 23);
        getContentPane().add(receivedby);
        receivedby.setBounds(750, 560, 190, 20);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(537, 633, 81, 66);

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setText("Particulars");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(33, 378, 160, 23);

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel5.setText("Product");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(34, 450, 150, 23);
        getContentPane().add(ae);
        ae.setBounds(240, 120, 228, 20);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Enter Customer ID");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(23, 120, 190, 17);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("FIND");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(520, 120, 69, 25);

        ac.setEditable(false);
        getContentPane().add(ac);
        ac.setBounds(240, 380, 230, 20);

        dateofentry.setEditable(false);
        getContentPane().add(dateofentry);
        dateofentry.setBounds(240, 310, 230, 20);

        jTextField3.setEditable(false);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(750, 310, 190, 20);

        setSize(new java.awt.Dimension(1020, 878));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void productKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productKeyReleased
        // TODO add your handling code here:

        int key=evt.getKeyCode();
        if(key==10)
        {
            quantities.requestFocus();// TODO add your handling code here:
        }
    }//GEN-LAST:event_productKeyReleased

    private void quantitiesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantitiesKeyReleased
        // TODO add your handling code here:

        int key=evt.getKeyCode();
        if(key==10)
        {
            invoiceno.requestFocus();// TODO add your handling code here:
        }
    }//GEN-LAST:event_quantitiesKeyReleased

    private void invoicenoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_invoicenoKeyReleased
        // TODO add your handling code here:

        int key=evt.getKeyCode();
        if(key==10)
        {
            invoiceamnt.requestFocus();// TODO add your handling code here:
        }
    }//GEN-LAST:event_invoicenoKeyReleased

    private void invoiceamntKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_invoiceamntKeyReleased
        // TODO add your handling code here:

        int key=evt.getKeyCode();
        if(key==10)
        {
          jTextField3.requestFocus();// TODO add your handling code here:
        }
    }//GEN-LAST:event_invoiceamntKeyReleased

    private void minoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_minoKeyReleased
        // TODO add your handling code here:

        int key=evt.getKeyCode();
        if(key==10)
        {
            qtyreceived.requestFocus();// TODO add your handling code here:
        }
    }//GEN-LAST:event_minoKeyReleased

    private void qtyreceivedKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyreceivedKeyReleased
        // TODO add your handling code here:
        int key=evt.getKeyCode();
        if(key==10)
        {
            remainingqnty.requestFocus();// TODO add your handling code here:
        }
    }//GEN-LAST:event_qtyreceivedKeyReleased

    private void serialnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_serialnoKeyReleased
        // TODO add your handling code here:

        int key=evt.getKeyCode();
        if(key==10)
        {
            dateofentry.requestFocus();// TODO add your handling code here:
        }
    }//GEN-LAST:event_serialnoKeyReleased

    private void remainingqntyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_remainingqntyKeyReleased
        // TODO add your handling code here:
        int key=evt.getKeyCode();
        if(key==10)
        {
            receivedby.requestFocus();// TODO add your handling code here:
        }
    }//GEN-LAST:event_remainingqntyKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         try
        {
            Class.forName("com.mysql.jdbc.Driver");
            
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/mis","root","");
            bb1=ae.getText();
            bb2=serialno.getText();
            bb3=jTextField1.getText();
            bb4=ac.getText();
            bb5=invoiceno.getText();
            bb6=product.getText();
            bb7=invoiceamnt.getText();
            bb8=quantities.getText();
            bb9=qtyreceived.getText();
            bb10=remainingqnty.getText();
            bb11=mino.getText();
            bb12=receivedby.getText();
            bb13=jTextField2.getText();
            String sql;
            sql="UPDATE purchase set Sl='"+bb2+"',Party_Name='"+bb3+"',Particulars='"+bb4+"',Invoice='"+bb5+"',Product='"+bb6+"',Amount='"+bb7+"',Quantity='"+bb8+"',Quantity_Recieved='"+bb9+"',Remaining_Quantity='"+bb10+"',Mi_No='"+bb11+"',Recieved_By='"+bb12+"',New_Due='"+bb13+"' where Customer_Id='"+bb1+"'";
             pst=conn.prepareStatement(sql);
            pst.execute();
            
            JOptionPane.showMessageDialog(null,"updated");
        }
        
        catch(Exception e)
        {
             JOptionPane.showMessageDialog(null,"PLEASE CHECK THE FIELDS AGAIN");
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
           Connection conn=null;
        ResultSet rs=null;
        PreparedStatement pst=null;
         try{
        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/mis","root","");
    String sql="select * from purchase where Customer_Id=?";
     pst=conn.prepareStatement(sql);
    pst.setString(1,ae.getText());
      rs=pst.executeQuery();
        if(rs.next())
        {
           jTextField1.setText(rs.getString("Party_Name"));
           serialno.setText(rs.getString("Sl"));
           dateofentry.setText(rs.getString("Order_Date"));
           ac.setText(rs.getString("Particulars"));
           product.setText(rs.getString("Product"));
           invoiceno.setText(rs.getString("Invoice"));
           int ad=rs.getInt("New_Due");
           jTextField2.setText(ad+"");
           int ma=rs.getInt("Quantity");
           quantities.setText(ma+"");
           int mb=rs.getInt("Amount");
           invoiceamnt.setText(mb+"");
           jTextField3.setText(rs.getString("Recieve_Date"));
           mino.setText(rs.getString("Mi_No"));
           int mc=rs.getInt("Quantity_Recieved");
           qtyreceived.setText(mc+"");
           int md=rs.getInt("Remaining_Quantity");
           remainingqnty.setText(md+"");
           receivedby.setText(rs.getString("Recieved_By"));
        }
    
    
     }
    catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    }

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updatepurchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updatepurchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updatepurchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updatepurchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updatepurchase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ac;
    private javax.swing.JTextField ae;
    private javax.swing.JTextField dateofentry;
    private javax.swing.JTextField invoiceamnt;
    private javax.swing.JTextField invoiceno;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField mino;
    private javax.swing.JTextArea product;
    private javax.swing.JTextField qtyreceived;
    private javax.swing.JTextField quantities;
    private javax.swing.JTextField receivedby;
    private javax.swing.JTextField remainingqnty;
    public javax.swing.JTextField serialno;
    // End of variables declaration//GEN-END:variables
}
