/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgfinal.java;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import static pkgfinal.java.updatecomplaint.bb1;

/**
 *
 * @author DELL
 */
public class updateenquiry extends javax.swing.JFrame {
     Connection conn=null;
        ResultSet rs=null;
        PreparedStatement pst=null;
         static String bb1,bb2,bb3,bb4,bb5,bb6,bb7,bb8,bb9,bb10,bb11,bb12,bb13,bb14,bb15,bb16,bb17;
    /**
     * Creates new form updateenquiry
     */
    public updateenquiry() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        company = new javax.swing.JTextField();
        location = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        customertype = new javax.swing.JTextField();
        remarks = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        othercontacts = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        products = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        ac = new javax.swing.JTextField();
        bc = new javax.swing.JTextField();
        cc = new javax.swing.JTextField();
        dc = new javax.swing.JTextField();
        ec = new javax.swing.JTextField();
        d1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Update Enquiry ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(12, 0, 453, 55);

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setText("Name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(12, 146, 130, 23);

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel5.setText("Company");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(12, 182, 130, 23);

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setText("Address");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(12, 223, 130, 23);

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel7.setText("Location");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(12, 264, 130, 23);

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel8.setText("Email");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(12, 305, 130, 23);

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel9.setText("Category");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(12, 346, 130, 23);

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel10.setText("Customer Type");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(12, 387, 180, 23);

        jLabel17.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel17.setText("Source");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(12, 428, 130, 23);

        jLabel18.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel18.setText("Remarks");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(12, 469, 130, 23);

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameKeyReleased(evt);
            }
        });
        getContentPane().add(name);
        name.setBounds(200, 150, 283, 20);

        company.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companyActionPerformed(evt);
            }
        });
        company.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                companyKeyReleased(evt);
            }
        });
        getContentPane().add(company);
        company.setBounds(200, 180, 283, 20);

        location.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationActionPerformed(evt);
            }
        });
        location.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                locationKeyReleased(evt);
            }
        });
        getContentPane().add(location);
        location.setBounds(200, 270, 283, 20);

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emailKeyReleased(evt);
            }
        });
        getContentPane().add(email);
        email.setBounds(200, 310, 283, 20);

        customertype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customertypeActionPerformed(evt);
            }
        });
        customertype.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                customertypeKeyReleased(evt);
            }
        });
        getContentPane().add(customertype);
        customertype.setBounds(200, 390, 283, 20);

        remarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remarksActionPerformed(evt);
            }
        });
        remarks.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                remarksKeyReleased(evt);
            }
        });
        getContentPane().add(remarks);
        remarks.setBounds(200, 470, 283, 89);

        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });
        address.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                addressKeyReleased(evt);
            }
        });
        getContentPane().add(address);
        address.setBounds(200, 230, 283, 20);

        jLabel19.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel19.setText("City");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(540, 180, 120, 23);

        phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneActionPerformed(evt);
            }
        });
        phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                phoneKeyReleased(evt);
            }
        });
        getContentPane().add(phone);
        phone.setBounds(730, 230, 273, 20);

        othercontacts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                othercontactsActionPerformed(evt);
            }
        });
        othercontacts.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                othercontactsKeyReleased(evt);
            }
        });
        getContentPane().add(othercontacts);
        othercontacts.setBounds(730, 270, 273, 20);

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel11.setText("Phone");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(540, 230, 120, 23);

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel12.setText("Other Contacts");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(540, 270, 160, 23);

        jLabel20.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel20.setText("Sub-Category");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(540, 390, 150, 23);

        products.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productsActionPerformed(evt);
            }
        });
        products.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                productsKeyReleased(evt);
            }
        });
        getContentPane().add(products);
        products.setBounds(730, 430, 273, 20);

        jLabel13.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel13.setText("Products");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(540, 430, 120, 23);

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel2.setText("Enquiry Type");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(540, 470, 140, 23);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(539, 549, 77, 23);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(805, 549, 71, 23);

        jLabel14.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel14.setText("Date");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(540, 140, 90, 16);

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setText("Customer_Id");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(12, 62, 160, 23);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(210, 60, 280, 20);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Find");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(510, 60, 57, 23);
        getContentPane().add(ac);
        ac.setBounds(200, 350, 283, 20);
        getContentPane().add(bc);
        bc.setBounds(200, 430, 280, 20);
        getContentPane().add(cc);
        cc.setBounds(730, 180, 273, 20);
        getContentPane().add(dc);
        dc.setBounds(730, 390, 273, 20);
        getContentPane().add(ec);
        ec.setBounds(730, 470, 273, 20);

        d1.setEditable(false);
        getContentPane().add(d1);
        d1.setBounds(730, 140, 273, 20);

        setSize(new java.awt.Dimension(1108, 759));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyReleased
        // TODO add your handling code here:
        int key=evt.getKeyCode();
        if(key==10)
        {
            company.requestFocus();// TODO add your handling code here:
        }
    }//GEN-LAST:event_nameKeyReleased

    private void companyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_companyActionPerformed

    private void companyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_companyKeyReleased
        // TODO add your handling code here:

        int key=evt.getKeyCode();
        if(key==10)
        {
            address.requestFocus();// TODO add your handling code here:
        }
    }//GEN-LAST:event_companyKeyReleased

    private void locationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locationActionPerformed

    private void locationKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_locationKeyReleased
        // TODO add your handling code here:
        int key=evt.getKeyCode();
        if(key==10)
        {
            email.requestFocus();// TODO add your handling code here:
        }
    }//GEN-LAST:event_locationKeyReleased

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void emailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailKeyReleased
        // TODO add your handling code here:
        int key=evt.getKeyCode();
        if(key==10)
        {
            ac.requestFocus();// TODO add your handling code here:
        }
    }//GEN-LAST:event_emailKeyReleased

    private void customertypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customertypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customertypeActionPerformed

    private void customertypeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_customertypeKeyReleased
        // TODO add your handling code here:
        int key=evt.getKeyCode();
        if(key==10)
        {
            bc.requestFocus();// TODO add your handling code here:
        }
    }//GEN-LAST:event_customertypeKeyReleased

    private void remarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remarksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_remarksActionPerformed

    private void remarksKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_remarksKeyReleased
        // TODO add your handling code here:
        int key=evt.getKeyCode();
        if(key==10)
        {
            d1.requestFocus();// TODO add your handling code here:
        }
    }//GEN-LAST:event_remarksKeyReleased

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void addressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addressKeyReleased
        // TODO add your handling code here:

        int key=evt.getKeyCode();
        if(key==10)
        {
            location.requestFocus();// TODO add your handling code here:
        }
    }//GEN-LAST:event_addressKeyReleased

    private void phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneActionPerformed

    private void phoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneKeyReleased
        // TODO add your handling code here:
        int key=evt.getKeyCode();
        if(key==10)
        {
            othercontacts.requestFocus();// TODO add your handling code here:
        }
    }//GEN-LAST:event_phoneKeyReleased

    private void othercontactsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_othercontactsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_othercontactsActionPerformed

    private void othercontactsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_othercontactsKeyReleased
        // TODO add your handling code here:
        int key=evt.getKeyCode();
        if(key==10)
        {
            dc.requestFocus();// TODO add your handling code here:
        }
    }//GEN-LAST:event_othercontactsKeyReleased

    private void productsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productsActionPerformed

    private void productsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productsKeyReleased
        // TODO add your handling code here:
        int key=evt.getKeyCode();
        if(key==10)
        {
            ec.requestFocus();// TODO add your handling code here:
        }
    }//GEN-LAST:event_productsKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      try
        {
            Class.forName("com.mysql.jdbc.Driver");
            
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/mis","root","");
            bb1=jTextField1.getText();
            bb2=name.getText();
            bb3=company.getText();
            bb4=address.getText();
            bb5=location.getText();
            bb6=email.getText();
            bb7=ac.getText();
            bb8=customertype.getText();
            bb9=bc.getText();
            bb10=remarks.getText();
            bb11=d1.getText();
            bb12=cc.getText();
            bb13=phone.getText();
            bb14=othercontacts.getText();
            bb15=dc.getText();
            bb16=products.getText();
            bb17=ec.getText();
            String sql;
            sql="UPDATE enquiry set Name='"+bb2+"',Company='"+bb3+"',Address='"+bb4+"',Location='"+bb5+"',Email='"+bb6+"',Category='"+bb7+"',Customer_Type='"+bb8+"',Sources='"+bb9+"',Remarks='"+bb10+"',Date='"+bb11+"',City='"+bb12+"',Phone='"+bb13+"',Other_Contact='"+bb14+"',Sub_Category='"+bb15+"',Product='"+bb16+"',Enquiry_Type='"+bb17+"' where Customer_Id='"+bb1+"'";
             pst=conn.prepareStatement(sql);
            pst.execute();
            
            JOptionPane.showMessageDialog(null,"updated");
        }
        
        catch(Exception e)
        {
             JOptionPane.showMessageDialog(null,"PLEASE CHECK THE FIELDS AGAIN");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
            Connection conn=null;
        ResultSet rs=null;
        PreparedStatement pst=null;
         try{
        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/mis","root","");
    String sql="select * from enquiry where Customer_Id=?";
     pst=conn.prepareStatement(sql);
    pst.setString(1,jTextField1.getText());
      rs=pst.executeQuery();
        if(rs.next())
        {
           name.setText(rs.getString("Name"));
           company.setText(rs.getString("Company"));
           address.setText(rs.getString("Address"));
           location.setText(rs.getString("Location"));
           email.setText(rs.getString("Email"));
           ac.setText(rs.getString("Category"));
           customertype.setText(rs.getString("Customer_Type"));
           bc.setText(rs.getString("Sources"));
           remarks.setText(rs.getString("Remarks"));
           d1.setText(rs.getString("Date"));
           cc.setText(rs.getString("City"));
           phone.setText(rs.getString("Phone"));
           othercontacts.setText(rs.getString("Other_Contact"));
           dc.setText(rs.getString("Sub_Category"));
           products.setText(rs.getString("Product"));
           ec.setText(rs.getString("Enquiry_Type"));
        
        }
    
    
     }
    catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateenquiry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateenquiry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateenquiry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateenquiry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateenquiry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ac;
    private javax.swing.JTextField address;
    private javax.swing.JTextField bc;
    private javax.swing.JTextField cc;
    private javax.swing.JTextField company;
    private javax.swing.JTextField customertype;
    private javax.swing.JTextField d1;
    private javax.swing.JTextField dc;
    private javax.swing.JTextField ec;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField location;
    private javax.swing.JTextField name;
    private javax.swing.JTextField othercontacts;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField products;
    private javax.swing.JTextField remarks;
    // End of variables declaration//GEN-END:variables
}
