/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgfinal.java;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class updateproduct extends javax.swing.JFrame {
    Connection conn=null;
        ResultSet rs=null;
        PreparedStatement pst=null;
        static String bb3,bb4,bb5,bb,bb6;
    /**
     * Creates new form updateproduct
     */
    public updateproduct() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        add_product = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        title = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        dealerprice = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        singleuserprice = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        remark = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        ac = new javax.swing.JTextField();
        bc = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        add_product.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add_product.setText("Update Product");
        add_product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_productActionPerformed(evt);
            }
        });
        getContentPane().add(add_product);
        add_product.setBounds(360, 460, 141, 25);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel8.setText("UPDATE PRODUCT");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 30, 250, 42);

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setText("Dealer Price");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 260, 200, 23);

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel5.setText("Single User Price");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 300, 230, 23);

        title.setEditable(false);
        title.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                titleKeyReleased(evt);
            }
        });
        getContentPane().add(title);
        title.setBounds(400, 210, 316, 20);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(570, 460, 77, 25);

        dealerprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dealerpriceActionPerformed(evt);
            }
        });
        dealerprice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dealerpriceKeyReleased(evt);
            }
        });
        getContentPane().add(dealerprice);
        dealerprice.setBounds(400, 250, 321, 20);

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setText("Remarks");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 360, 170, 23);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setText("Category");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 140, 180, 23);

        singleuserprice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                singleuserpriceKeyReleased(evt);
            }
        });
        getContentPane().add(singleuserprice);
        singleuserprice.setBounds(400, 290, 321, 20);

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel2.setText("Sub- Category");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 180, 220, 23);
        getContentPane().add(remark);
        remark.setBounds(400, 340, 321, 84);

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setText("Title");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 220, 140, 23);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Enter Product's Title");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(80, 90, 250, 31);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(400, 90, 310, 20);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("FIND");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(780, 100, 69, 25);

        ac.setEditable(false);
        getContentPane().add(ac);
        ac.setBounds(400, 130, 316, 20);

        bc.setEditable(false);
        getContentPane().add(bc);
        bc.setBounds(400, 170, 316, 20);

        setSize(new java.awt.Dimension(931, 661));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void add_productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_productActionPerformed
 try
        {
            Class.forName("com.mysql.jdbc.Driver");
            
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/mis","root","");
            bb3=title.getText();
            bb4=dealerprice.getText();
            bb5=singleuserprice.getText();
            bb6=remark.getText();
            String sql;
            sql="UPDATE product set Dealer_Price='"+bb4+"',Single_User_Price='"+bb5+"',Remarks='"+bb6+"' where Title='"+bb3+"'";
             pst=conn.prepareStatement(sql);
            pst.execute();
            
            JOptionPane.showMessageDialog(null,"updated");
        }
        
        catch(Exception e)
        {
             JOptionPane.showMessageDialog(null,"PLEASE CHECK THE FIELDS AGAIN");
        }
    }//GEN-LAST:event_add_productActionPerformed

    private void titleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_titleKeyReleased
        // TODO add your handling code here:
        int key=evt.getKeyCode();
        if(key==10)
        {
            dealerprice.requestFocus();// TODO add your handling code here:
        }
    }//GEN-LAST:event_titleKeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void dealerpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dealerpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dealerpriceActionPerformed

    private void dealerpriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dealerpriceKeyReleased
        // TODO add your handling code here:
        int key=evt.getKeyCode();
        if(key==10)
        {
            singleuserprice.requestFocus();// TODO add your handling code here:
        }
    }//GEN-LAST:event_dealerpriceKeyReleased

    private void singleuserpriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_singleuserpriceKeyReleased
        // TODO add your handling code here:
        int key=evt.getKeyCode();
        if(key==10)
        {
            remark.requestFocus();// TODO add your handling code here:
        }
    }//GEN-LAST:event_singleuserpriceKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
           Connection conn=null;
        ResultSet rs=null;
        PreparedStatement pst=null;
         try{
        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/mis","root","");
    String sql="select * from product where title=?";
     pst=conn.prepareStatement(sql);
    pst.setString(1,jTextField1.getText());
      rs=pst.executeQuery();
        if(rs.next())
        {
           ac.setText(rs.getString("Category"));
           bc.setText(rs.getString("Sub_Category"));
           title.setText(rs.getString("Title"));
           int mb=rs.getInt("Dealer_Price");
           dealerprice.setText(mb+"");
           int ma=rs.getInt("Single_User_Price");
           singleuserprice.setText(ma+"");
           remark.setText(rs.getString("Remarks"));
        
        }
    
    
     }
    catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateproduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateproduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateproduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateproduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateproduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ac;
    private javax.swing.JButton add_product;
    private javax.swing.JTextField bc;
    private javax.swing.JTextField dealerprice;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField remark;
    private javax.swing.JTextField singleuserprice;
    private javax.swing.JTextField title;
    // End of variables declaration//GEN-END:variables
}
