/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgfinal.java;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class updatesales extends javax.swing.JFrame {
    Connection conn=null;
        ResultSet rs=null;
        PreparedStatement pst=null;
        static String bb13,bb14,bb1,bb2,bb3,bb4,bb5,bb,bb6,bb7,bb8,bb9,bb10,bb11,bb12;

    /**
     * Creates new form updatesales
     */
    public updatesales() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        a = new javax.swing.JTextField();
        c = new javax.swing.JTextField();
        h1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        i = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        j = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        k = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        d = new javax.swing.JTextField();
        e = new javax.swing.JTextField();
        f = new javax.swing.JTextField();
        g = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        b = new javax.swing.JTextField();
        i1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel7.setText("Product Amount");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 320, 200, 23);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton3.setText("CANCEL");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(690, 450, 81, 55);

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel8.setText("Dispatched Through");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 360, 200, 23);

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel9.setText("Remaining Quantity");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 410, 220, 23);

        a.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                aKeyReleased(evt);
            }
        });
        getContentPane().add(a);
        a.setBounds(760, 320, 200, 20);

        c.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cKeyReleased(evt);
            }
        });
        getContentPane().add(c);
        c.setBounds(270, 240, 190, 20);

        h1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                h1KeyReleased(evt);
            }
        });
        getContentPane().add(h1);
        h1.setBounds(760, 120, 200, 20);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Customer Name");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(40, 110, 170, 30);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(270, 120, 190, 20);

        jLabel14.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel14.setText("Material Outward No.");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(510, 270, 220, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("New Due");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(510, 360, 150, 20);

        i.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                iKeyReleased(evt);
            }
        });
        getContentPane().add(i);
        i.setBounds(760, 200, 200, 20);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(760, 360, 200, 20);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Update Sales");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 10, 262, 32);

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel2.setText("No. Of Entry");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(510, 320, 160, 30);

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setText("Date Of Entry");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 160, 170, 23);

        j.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jKeyReleased(evt);
            }
        });
        getContentPane().add(j);
        j.setBounds(760, 240, 200, 20);

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setText("Particulars");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 200, 170, 23);
        getContentPane().add(k);
        k.setBounds(760, 280, 200, 20);

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel5.setText("Product");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 240, 150, 23);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("UPDATE SALES");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(480, 450, 123, 55);

        d.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dKeyReleased(evt);
            }
        });
        getContentPane().add(d);
        d.setBounds(270, 280, 190, 20);

        e.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                eKeyReleased(evt);
            }
        });
        getContentPane().add(e);
        e.setBounds(270, 320, 190, 20);

        f.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fKeyReleased(evt);
            }
        });
        getContentPane().add(f);
        f.setBounds(270, 360, 190, 20);

        g.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                gKeyReleased(evt);
            }
        });
        getContentPane().add(g);
        g.setBounds(270, 410, 190, 20);

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel10.setText("Quantity");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(510, 110, 160, 30);

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel11.setText("Date Of Invoice");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(510, 150, 210, 30);

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel12.setText("Dispatched Quantity");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(510, 190, 220, 30);

        jLabel13.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel13.setText("Gate Pass No.");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(510, 230, 180, 30);

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setText("Invoice No");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 280, 180, 23);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Enter Customer ID");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(30, 60, 190, 26);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(260, 60, 268, 20);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("FIND");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(610, 60, 61, 23);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(270, 200, 190, 20);

        b.setEditable(false);
        getContentPane().add(b);
        b.setBounds(270, 160, 190, 20);

        i1.setEditable(false);
        getContentPane().add(i1);
        i1.setBounds(760, 160, 200, 20);

        setSize(new java.awt.Dimension(1080, 622));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void aKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aKeyReleased
        // TODO add your handling code here:

        int key=evt.getKeyCode();
        if(key==10)
        {
            b.requestFocus();
        }
    }//GEN-LAST:event_aKeyReleased

    private void cKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cKeyReleased
        // TODO add your handling code here:
        int key=evt.getKeyCode();
        if(key==10)
        {
            d.requestFocus();// TODO add your handling code here:
        }
    }//GEN-LAST:event_cKeyReleased

    private void h1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_h1KeyReleased
        // TODO add your handling code here:
        int key=evt.getKeyCode();
        if(key==10)
        {
            i1.requestFocus();// TODO add your handling code here:
        }
    }//GEN-LAST:event_h1KeyReleased

    private void iKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_iKeyReleased
        // TODO add your handling code here:
        int key=evt.getKeyCode();
        if(key==10)
        {
            j.requestFocus();// TODO add your handling code here:
        }
    }//GEN-LAST:event_iKeyReleased

    private void jKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jKeyReleased
        // TODO add your handling code here:
        int key=evt.getKeyCode();
        if(key==10)
        {
            k.requestFocus();// TODO add your handling code here:
        }
    }//GEN-LAST:event_jKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          try
        {
            Class.forName("com.mysql.jdbc.Driver");
            
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/mis","root","");
            bb1=jTextField3.getText();
            bb2=jTextField1.getText();
            bb3=jTextField4.getText();
            bb4=d.getText();
            bb5=c.getText();
            bb6=e.getText();
            bb7=a.getText();
            bb8=f.getText();
            bb9=h1.getText();
            bb10=i.getText();
            bb11=g.getText();
            bb12=j.getText();
            bb13=k.getText();
            bb14=jTextField2.getText();
            String sql;
            sql="UPDATE sales set Customer_Id='"+bb1+"', Customer_Name='"+bb2+"',Particulars='"+bb3+"',Invoice_No='"+bb4+"',Product='"+bb5+"',Product_Amt='"+bb6+"',No_Of_Entry='"+bb7+"',Dispatched_Through='"+bb8+"',Quantity='"+bb9+"',Dispatched_Quantity='"+bb10+"',Remaining_Quantity='"+bb11+"',Gate_Pass_No='"+bb12+"',Material_Outward_no='"+bb13+"',New_Due='"+bb14+"' where Customer_Id='"+bb1+"'";
             pst=conn.prepareStatement(sql);
            pst.execute();
            
            JOptionPane.showMessageDialog(null,"updated");
        }
        
        catch(Exception e)
        {
             JOptionPane.showMessageDialog(null,"PLEASE CHECK THE FIELDS AGAIN");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void dKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dKeyReleased
        // TODO add your handling code here:
        int key=evt.getKeyCode();
        if(key==10)
        {
            e.requestFocus();// TODO add your handling code here:
        }
    }//GEN-LAST:event_dKeyReleased

    private void eKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_eKeyReleased
        // TODO add your handling code here:
        int key=evt.getKeyCode();
        if(key==10)
        {
            f.requestFocus();// TODO add your handling code here:
        }
    }//GEN-LAST:event_eKeyReleased

    private void fKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fKeyReleased
        // TODO add your handling code here:
        int key=evt.getKeyCode();
        if(key==10)
        {
            g.requestFocus();// TODO add your handling code here:
        }
    }//GEN-LAST:event_fKeyReleased

    private void gKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gKeyReleased
        // TODO add your handling code here:
        int key=evt.getKeyCode();
        if(key==10)
        {
            h1.requestFocus();// TODO add your handling code here:
        }
    }//GEN-LAST:event_gKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          Connection conn=null;
        ResultSet rs=null;
        PreparedStatement pst=null;
         try{
        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/mis","root","");
    String sql="select * from sales where Customer_Id=?";
     pst=conn.prepareStatement(sql);
    pst.setString(1,jTextField3.getText());
      rs=pst.executeQuery();
        if(rs.next())
        {
           jTextField1.setText(rs.getString("Customer_Name"));
           b.setText(rs.getString("Date_of_Entry"));
           jTextField4.setText(rs.getString("Particulars"));
           c.setText(rs.getString("Product"));
           d.setText(rs.getString("Invoice_No"));
           int mb=rs.getInt("Product_Amt");
           e.setText(mb+"");
           f.setText(rs.getString("Dispatched_Through"));
           int md=rs.getInt("Remaining_Quantity");
           g.setText(md+"");
           int ma=rs.getInt("Quantity");
           h1.setText(ma+"");
           i1.setText(rs.getString("Date_of_Invoice"));
           int mc=rs.getInt("Dispatched_Quantity");
           i.setText(mc+"");
           j.setText(rs.getString("Gate_Pass_No"));
           int bd=rs.getInt("Material_Outward_No");
           k.setText(bd+"");
           int cd=rs.getInt("No_of_Entry");
           a.setText(cd+"");
           int ad=rs.getInt("New_Due");
           jTextField2.setText(ad+"");
      
        }
    
    
     }
    catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updatesales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updatesales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updatesales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updatesales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updatesales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a;
    private javax.swing.JTextField b;
    private javax.swing.JTextField c;
    private javax.swing.JTextField d;
    private javax.swing.JTextField e;
    private javax.swing.JTextField f;
    private javax.swing.JTextField g;
    private javax.swing.JTextField h1;
    private javax.swing.JTextField i;
    private javax.swing.JTextField i1;
    private javax.swing.JTextField j;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField k;
    // End of variables declaration//GEN-END:variables
}
